### ISSUE TITLE
Bug Bite/Pluck crash

### ISSUE THREAD

**Issue by GengarFan95** [git-afsantos/crystal50#10]
When I let my Pokemon use Bug Bite or Pluck against a Pokemon that holds a Berry, the game crashes

**Comment by oatspear** [comment]
Hey, @GengarFan95 ! Thanks for trying out the game, and thanks for reporting this issue.
I will look into it and try to provide a fix 🔧

**Comment by oatspear** [comment]
It took me a while to get back into this project, but [release v1.1.1](https://github.com/oatspear/crystal50/releases/tag/v1.1.1) should have fixed this.
